import { uid } from 'uid';
import TEXTS from '../texts/texts';
import {
  DiagServiceIcon,
  EngineServiceIcon,
  WheelServiceIcon,
  OilServiceIcon,
  BodyServiceIcon,
  BatteryServiceIcon,
  IncurServiceIcon,
  CustomServiceIcon,
} from '../../assets/icons';

const SERVICES = [
  {
    id: uid(),
    text: `${TEXTS.services.diag}`,
    logo: <DiagServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.engine}`,
    logo: <EngineServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.wheel}`,
    logo: <WheelServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.oil}`,
    logo: <OilServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.body}`,
    logo: <BodyServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.batteries}`,
    logo: <BatteryServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.insur}`,
    logo: <IncurServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.custom}`,
    logo: <CustomServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.wash}`,
    logo: <DiagServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
  {
    id: uid(),
    text: `${TEXTS.services.ac}`,
    logo: <EngineServiceIcon />,
    title1: `${TEXTS.servicePage.title1}`,
    paragraph1: `${TEXTS.servicePage.paragraph1}`,
    title2: `${TEXTS.servicePage.title2}`,
    paragraph2: `${TEXTS.servicePage.paragraph2}`,
    quote: `${TEXTS.servicePage.quote}`,
  },
];

export default SERVICES;
